# Generated by Django 5.1.4 on 2024-12-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Doctor'), (3, 'Nurse'), (1, 'Admin')], null=True),
        ),
    ]
